# Generated by Django 5.1.4 on 2025-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_relative_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
