# Generated by Django 5.1.4 on 2025-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_person_relative_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.ImageField(default='service_images/default.png', upload_to='service_images/'),
        ),
    ]
