# Generated by Django 5.1.4 on 2025-02-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_rating_report_services_request_payment_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='category_id',
            new_name='category',
        ),
    ]
