# Generated by Django 5.1.4 on 2025-02-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_id_services_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='service_id',
            new_name='service',
        ),
    ]
