# Generated by Django 5.1.4 on 2025-02-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rating_stars_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='ProviderRating',
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('comment', models.TextField()),
                ('rated_date', models.DateTimeField(auto_now_add=True)),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
