# Generated by Django 5.1.4 on 2025-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rating_providerrating_servicerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
