# Generated by Django 5.1.4 on 2025-01-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
