# Generated by Django 5.1.4 on 2025-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_avatarurl_user_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(default='assets/images/default_profile.png', max_length=100),
        ),
    ]
